name: mld-box-model
channels:
  - conda-forge
dependencies:
  - python=3.9
  - matplotlib>=3.4.0,<3.5.0
  - numpy>=1.21.0,<1.22.0
  - pillow>=9.0.0,<10.0.0
  - scipy>=1.5.0,<1.7.0
  - h5py>=3.0.0,<3.2.0
  - pandas>=1.2.0,<1.3.0
  - pyco2sys==1.8.3.2
  - pytables>=3.6.0,<3.7.0